### PR TITLE
Add WCAG 2.2 and EN 301 549 data, update to VPAT 2.5, refactor Librarian

### PR DESCRIPTION
**Pull request by patrickhlauke**
* add new `/catalog/data/wcag-2.2.yaml` to include all new SCs (note: keeps 4.1.1 as it is still reportable)
* add new `/catalog/data/en-301-549.yaml` (using as starting point the data that was already added by hand to `/catalog/2.4-edition-wcag-2.1-508-eu-en.yaml`)
* update terms and any references to VPAT version number to new ITI VPAT 2.5 https://www.itic.org/policy/accessibility/vpat
* refactor Librarian utility (and associated `createCatalog`) to better handle combining an arbitrary amount (array) of standards
* add support for VPAT 2.5 INT (the only version not supported yet is the pure EU version, as this will require re-numbering of chapters in final document - this should be done as one big separate update that runs at the end over the combined output and makes sure chapter numbers are properly sequential)
* add generated yaml files for all the catalog variants the Librarian now supports (note: left the previous 2.4 versions in place...this may require further planning/thinking on how these old versions should be maintained or generated ... perhaps librarian needs an extra version switch for VPAT too?)

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Note that this may need more work in other parts of the project - I focused purely on the `/catalog` and related Librarian generation parts

**Comment by thibaudcolas** [comment]
For what it’s worth – I tried updating my report based on `2.4-edition-wcag-2.1-508-eu-en.yaml` to the new 2.5 edition WCAG 2.2 here, it worked great 🌈. All I had to do was manually add the data for the additional SCs in my YAML report, then use the CLI with this PR to output Markdown and HTML. Thank you!

**Comment by patrickhlauke** [comment]
thanks for checking, @thibaudcolas - admittedly, I made this PR "cold" without actually trying it out. I do suspect this will require some work on related projects like https://github.com/GSA/openacr-editor

additionally, note that unfortunately for the EU standard, it seems there's only a PDF version officially available, so the `alt_id` references are made-up and don't actually point back to the relevant section in the PDF. not sure if these should therefore just be left blank, or changed to reference just the `#page=...` number for the PDF, or something else...

**Comment by dmundra** [comment]
@patrickhlauke I submitted a PR to these changes by forking your repo https://github.com/patrickhlauke/openacr/pull/1, it should fix the tests and make a few modifications.

**Comment by patrickhlauke** [comment]
@dmundra merged your PR into my branch, which I can see updated the PR here

**Review by drewnielson — APPROVED** [review]

**Pull request merged**
